from __future__ import annotations

from pathlib import Path


def test_meta_contract_runbooks_lock_latest_reason_scope_wording() -> None:
    expected_lines = [
        "`execution contract summary`",
        "`execution contract entry scope`",
        "`execution contract wording lock`",
        "`symmetry_regression_test`",
        "`execution_contract_symmetry_lock_included=True`",
        "`symmetry_fields`",
        "`symmetry_field_set`",
        "`symmetry_field_map`",
        "`symmetry_contract_bundle`",
        "`symmetry_contract_ready=True`",
        "`symmetry_contract_stack_complete=True`",
        "`symmetry_reason_scope`",
        "`symmetry_reason_range_summary`",
        "`symmetry_reason_final_summary`",
        "`symmetry_contract_status`",
        "`symmetry_contract_summary_ready=True`",
        "`symmetry_contract_topline_verdict`",
        "`execution_meta_contract_test_index_symmetry_fields`",
        "`execution_contract_symmetry_regression_test`",
        "`execution_contract_symmetry_fields`",
        "`execution_contract_symmetry_field_set`",
        "`execution_contract_symmetry_field_map`",
        "`execution_contract_symmetry_contract_bundle`",
        "`execution_contract_symmetry_ready=True`",
        "`execution_contract_symmetry_stack_complete=True`",
        "`execution_contract_symmetry_reason_scope`",
        "`execution_contract_symmetry_reason_range_summary`",
        "`execution_contract_symmetry_reason_final_summary`",
        "`execution_contract_symmetry_status`",
        "`execution_contract_symmetry_summary_ready=True`",
        "`execution_contract_symmetry_topline_verdict=symmetry contract topline | complete`",
        "`meta_contract_topline_regression_test`",
        "`meta_contract_topline_regression_test=tests/unit/test_btc_1d_meta_contract_wording_contract.py`",
        "`meta_contract_topline_reason_wording_included=True`",
        "`meta_contract_topline_status`",
        "`meta_contract_topline_status=meta topline status | regression_test=tests/unit/test_btc_1d_meta_contract_wording_contract.py | reason_included=True`",
        "`meta_contract_topline_quick_status`",
        "`meta_contract_topline_quick_status=meta topline quick | lock=ok | reason=included`",
        "`meta_contract_topline_highlight`",
        "`meta_contract_topline_highlight=topline highlight | lock=ok | reason=included`",
        "`meta_contract_reason_highlight_summary`",
        "`meta_contract_reason_highlight_summary=reason+highlight | summary_ready | reason=included`",
        "`meta_contract_reason_final_verdict`",
        "`meta_contract_reason_final_verdict=reason final verdict | complete | reason=included`",
        "`meta_contract_integrated_topline_verdict`",
        "`meta_contract_integrated_topline_verdict=meta contract integrated | topline=complete | reason=complete`",
        "execution contract screen should also expose `meta_contract_integrated_topline_verdict`",
        "execution contract screen should also expose `execution_meta_quick_status`",
        "execution contract screen should also expose `execution_meta_integrated_quick_verdict`",
        "execution contract screen should also expose `execution_meta_topline_bundle`",
        "execution contract screen should also expose `execution_meta_bundle_ready_verdict`",
        "execution contract screen should also expose `execution_meta_topline_ready`",
        "execution contract screen should also expose `execution_meta_stack_complete`",
        "meta contract screen should also expose `execution_meta_quick_status`",
        "meta contract screen should also expose `execution_meta_integrated_quick_verdict`",
        "meta contract screen should also expose `execution_meta_topline_bundle`",
        "meta contract screen should also expose `execution_meta_bundle_ready_verdict`",
        "meta contract screen should also expose `execution_meta_topline_ready`",
        "meta contract screen should also expose `execution_meta_stack_complete`",
        "`execution_meta_quick_status=execution+meta quick | execution=complete | meta=complete`",
        "`execution_meta_integrated_quick_verdict=execution+meta integrated | execution=complete | meta=complete`",
        "`execution_meta_topline_bundle=execution+meta topline bundle | quick=execution+meta quick | execution=complete | meta=complete | integrated=execution+meta integrated | execution=complete | meta=complete`",
        "`execution_meta_bundle_ready_verdict=execution+meta bundle ready | complete`",
        "`execution_meta_topline_ready=execution+meta topline ready | complete`",
        "`execution_meta_stack_complete=execution+meta stack complete | complete`",
        "`execution_meta_quick_status/execution_meta_integrated_quick_verdict/execution_meta_topline_bundle/execution_meta_bundle_ready_verdict/execution_meta_topline_ready/execution_meta_stack_complete should stay aligned across the execution contract summary`",
        "`execution_meta_quick_status/execution_meta_integrated_quick_verdict/execution_meta_topline_bundle/execution_meta_bundle_ready_verdict/execution_meta_topline_ready/execution_meta_stack_complete`",
        "`execution_meta_quick_status/.../execution_meta_stack_complete field-set reason wording`",
        "`execution_meta_quick_status/.../execution_meta_stack_complete final sentence wording`",
        "`tests/unit/test_btc_1d_meta_contract_wording_contract.py`",
        "`execution contract wording lock, meta_contract_topline_regression_test, and execution contract symmetry key/set/map/bundle/ready/stack_complete/summary_ready metadata`",
        "`execution contract symmetry key/set/map/bundle/ready/stack_complete/summary_ready metadata`",
        "`execution contract symmetry key/set/map/bundle/ready/stack_complete/summary_ready metadata, and execution_meta_quick_status/execution_meta_integrated_quick_verdict/execution_meta_topline_bundle/execution_meta_bundle_ready_verdict/execution_meta_topline_ready/execution_meta_stack_complete.`",
        "`reverse_screen_pointer_lock_included`",
        "`reverse_screen_pointer_lock_scope=['execution_contract_screen_summary']`",
        "`reverse_screen_pointer_lock_scope=['meta_contract_screen_summary']`",
        "`reverse_screen_pointer_scope_regression_test`",
    ]
    paths = [
        Path(r"C:\AI\Crypto\docs\operator_runbook.md"),
        Path(r"C:\AI\Crypto\docs\btc_1d_shadow_update_runbook.md"),
    ]

    for path in paths:
        text = path.read_text(encoding="utf-8")
        for expected in expected_lines:
            assert expected in text, f"{expected} missing from {path}"
